name: Acceptance Tests
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--diff --color"
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: '*.txt'
      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install tox
      - run: tox -e py39
#      - uses: actions/setup-go@v3
#        with:
#          go-version: ^1.18
#      - uses: actions/checkout@v3
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v3
#        with:
#          args: --timeout 4m0s
#  vet:
#    name: Vet
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Vet
#        run: go vet ./...
#  test:
#    name: Test
#    needs: [ build ]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v3
#        with:
#          go-version: ^1.18
#      - name: Run tests
#        run: |
#         make test
#        env:
#         GOPATH: /home/runner/work/cli/go